SELECT FCR.FORM_NAME, 
       FCR.FUNCTION_NAME,
       FCR.SEQUENCE,
       FCR.DESCRIPTION,
       FCR.CONDITION,
       FCA.SEQUENCE ACTION_SEQUENCE,
       FCA.PROPERTY_VALUE,
       FCA.BUILTIN_ARGUMENTS,
       FCA.MESSAGE_TEXT,
       FCA.MENU_ARGUMENT_LONG
FROM   FND_FORM_CUSTOM_RULES   FCR,
       FND_FORM_CUSTOM_ACTIONS FCA
WHERE  FCR.ID = FCA.RULE_ID
AND    ( FCA.PROPERTY_VALUE     LIKE '%\_TL%' ESCAPE '\' OR
         FCA.PROPERTY_VALUE     LIKE '%FND\_LOOKUP\_VALUES%' ESCAPE '\' OR
         FCA.BUILTIN_ARGUMENTS  LIKE '%\_TL%' ESCAPE '\' OR
         FCA.BUILTIN_ARGUMENTS  LIKE '%FND\_LOOKUP\_VALUES%' ESCAPE '\' OR
         FCA.MESSAGE_TEXT       LIKE '%\_TL%' ESCAPE '\' OR
         FCA.MESSAGE_TEXT       LIKE '%FND\_LOOKUP\_VALUES%' ESCAPE '\' OR
         FCA.MENU_ARGUMENT_LONG LIKE '%\_TL%' ESCAPE '\' OR
         FCA.MENU_ARGUMENT_LONG LIKE '%FND\_LOOKUP\_VALUES%' ESCAPE '\' )
ORDER  BY
       FCR.FORM_NAME, 
       FCR.FUNCTION_NAME,
       FCR.SEQUENCE,
       FCA.SEQUENCE
--AND    FCR.CONDITION


