SELECT APP.APPLICATION_NAME,
       FDF.TITLE,
       FDF.DESCRIPTIVE_FLEXFIELD_NAME,
       CTX.DESCRIPTIVE_FLEX_CONTEXT_CODE,
       USG.APPLICATION_COLUMN_NAME,
       USG.END_USER_COLUMN_NAME,
       USG.*
FROM   FND_DESCRIPTIVE_FLEXS_VL     FDF,
       FND_APPLICATION_VL           APP,
       FND_DESCR_FLEX_CONTEXTS_VL   CTX,
       FND_DESCR_FLEX_COL_USAGE_VL  USG
WHERE  FDF.APPLICATION_ID = APP.APPLICATION_ID
AND    FDF.DESCRIPTIVE_FLEXFIELD_NAME NOT LIKE '$SRS$.%'
AND    FDF.APPLICATION_ID = CTX.APPLICATION_ID
AND    FDF.DESCRIPTIVE_FLEXFIELD_NAME = CTX.DESCRIPTIVE_FLEXFIELD_NAME
AND    CTX.ENABLED_FLAG = 'Y'
AND    CTX.APPLICATION_ID = USG.APPLICATION_ID
AND    CTX.DESCRIPTIVE_FLEXFIELD_NAME = USG.DESCRIPTIVE_FLEXFIELD_NAME
AND    CTX.DESCRIPTIVE_FLEX_CONTEXT_CODE = USG.DESCRIPTIVE_FLEX_CONTEXT_CODE
AND    USG.ENABLED_FLAG = 'Y'
AND    USG.DEFAULT_TYPE = 'S' -- Default type is SQL Statement
AND    ( USG.DEFAULT_VALUE LIKE '%\_TL%' ESCAPE '\' OR
         USG.DEFAULT_VALUE LIKE '%FND_LOOKUP_VALUES%' )
