SELECT APP.APPLICATION_NAME,
       PROG.CONCURRENT_PROGRAM_NAME,
       PROG.USER_CONCURRENT_PROGRAM_NAME,
       USG.COLUMN_SEQ_NUM,
       USG.END_USER_COLUMN_NAME,
       USG.DEFAULT_VALUE
FROM   FND_CONCURRENT_PROGRAMS_VL  PROG,
       FND_APPLICATION_VL          APP,
       FND_DESCR_FLEX_COL_USAGE_VL USG
WHERE  PROG.APPLICATION_ID = APP.APPLICATION_ID
AND    PROG.ENABLED_FLAG = 'Y'
AND    ( PROG.CONCURRENT_PROGRAM_NAME LIKE 'XX%'  OR
         PROG.CONCURRENT_PROGRAM_NAME LIKE 'CUX%' OR
         PROG.CONCURRENT_PROGRAM_NAME LIKE 'EMR%' OR
         PROG.USER_CONCURRENT_PROGRAM_NAME LIKE 'EMR%' )
AND    PROG.APPLICATION_ID = USG.APPLICATION_ID
AND    '$SRS$.' || PROG.CONCURRENT_PROGRAM_NAME = USG.DESCRIPTIVE_FLEXFIELD_NAME
AND    USG.ENABLED_FLAG = 'Y'
AND    USG.DEFAULT_TYPE = 'S'
AND    ( USG.DEFAULT_VALUE LIKE '%\_TL%' ESCAPE '\' OR
         USG.DEFAULT_VALUE LIKE '%FND_LOOKUP_VALUES%' )
ORDER BY APP.APPLICATION_NAME,
         PROG.USER_CONCURRENT_PROGRAM_NAME,
         USG.COLUMN_SEQ_NUM;
