SELECT APP.APPLICATION_NAME,
       FLX.ID_FLEX_NAME,
       STRT.ID_FLEX_STRUCTURE_CODE,
       STRT.ID_FLEX_STRUCTURE_NAME,
       SEG.APPLICATION_COLUMN_NAME,
       SEG.SEGMENT_NAME,
       SEG.DEFAULT_VALUE
FROM   FND_ID_FLEXS              FLX,
       FND_APPLICATION_VL        APP,
       FND_ID_FLEX_STRUCTURES_VL STRT,
       FND_ID_FLEX_SEGMENTS_VL   SEG
WHERE  FLX.APPLICATION_ID = APP.APPLICATION_ID
AND    FLX.APPLICATION_ID = STRT.APPLICATION_ID
AND    FLX.ID_FLEX_CODE   = STRT.ID_FLEX_CODE
AND    STRT.ENABLED_FLAG = 'Y'
AND    STRT.APPLICATION_ID = SEG.APPLICATION_ID
AND    STRT.ID_FLEX_CODE = SEG.ID_FLEX_CODE
AND    STRT.ID_FLEX_NUM = SEG.ID_FLEX_NUM
AND    SEG.ENABLED_FLAG = 'Y'
AND    SEG.DEFAULT_TYPE = 'S'
AND    ( SEG.DEFAULT_VALUE LIKE '%\_TL%' ESCAPE '\' OR
         SEG.DEFAULT_VALUE LIKE '%FND_LOOKUP_VALUES%' )
