SELECT FVS.FLEX_VALUE_SET_NAME, 
       FVT.APPLICATION_TABLE_NAME,
       LONG_TO_CHAR(FVT.ROWID, 'APPS', 'FND_FLEX_VALIDATION_TABLES', 'ADDITIONAL_WHERE_CLAUSE') ADDITIONAL_WHERE_CLAUSE
FROM   FND_FLEX_VALUE_SETS        FVS,
       FND_FLEX_VALIDATION_TABLES FVT
WHERE  FVT.FLEX_VALUE_SET_ID = FVS.FLEX_VALUE_SET_ID
AND    FVS.VALIDATION_TYPE = 'F'
AND    ( FVS.FLEX_VALUE_SET_NAME LIKE 'XX%' OR
         FVS.FLEX_VALUE_SET_NAME LIKE 'CUX%' OR
         FVS.FLEX_VALUE_SET_NAME LIKE 'EMR%')
AND    ( FVT.APPLICATION_TABLE_NAME  LIKE '%\_TL%' ESCAPE '\' OR
         FVT.APPLICATION_TABLE_NAME  LIKE '%FND_LOOKUP_VALUES%' OR
         LONG_TO_CHAR(FVT.ROWID, 'APPS', 'FND_FLEX_VALIDATION_TABLES', 'ADDITIONAL_WHERE_CLAUSE')
         LIKE '%\_TL%' ESCAPE '\' OR
         LONG_TO_CHAR(FVT.ROWID, 'APPS', 'FND_FLEX_VALIDATION_TABLES', 'ADDITIONAL_WHERE_CLAUSE')
         LIKE '%FND_LOOKUP_VALUES%' )
ORDER BY FVS.FLEX_VALUE_SET_NAME
